name: Result evaluation

inputs:
  size:
    description: "What dataset size to run experiments for"
    required: true
    default: "100M"
    type: string

runs:
  using: "composite"
  steps:
    - name: Evaluate results
      shell: bash -el {0}
      run: |
        conda activate hiob
        python3 eval/eval.py --data data --results result/clip768v2 res.csv
    - uses: actions/upload-artifact@v3
      with:
        name: Results on ${{ inputs.size }}
        path: | 
          res.csv
