name: Test run

on:
  workflow_dispatch:
    inputs:
      k:
        description: "Number of neighbors to search. Must be in [0,100]"
        required: true
        default: 30
        type: number

jobs:
  test:
    name: Testing Task 1 execution on 300K dataset
    strategy:
      fail-fast: false
      matrix:
        version:
          - '1.8'
        os:
          - ubuntu-latest
        arch:
          - x64
        exclude:
          - os: macOS-latest
            arch: x86
        python-version: ["3.11.2"]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: 'true'
      - uses: ./.github/actions/system_setup
        with:
          python-version: ${{ matrix.python-version }}
      - name: Run benchmark (no tuning)
        shell: bash -el {0}
        run: |
          conda activate hiob
          rust-search/target/release/rust-search \
            -i data -o result \
            --its 10000 \
            --samples 10000 \
            --batch-its 1000 \
            --k ${{ inputs.k }} \
            --size 300K \
            --bits 64 \
            --noise 0.05 \
            --probe-min 3300 \
            --probe-max 5000 \
            --probe-steps 10 \
            --itq \
            --ram \
            --refine
      - uses: ./.github/actions/evaluation
        with:
          os: ${{ matrix.os }}
          size: 300K
